// Derives the SQLite variant of the Prisma schema from the canonical PostgreSQL one.
// Prisma does not allow switching providers at runtime, so dev/test use this generated copy.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = readFileSync(resolve(root, 'prisma/schema.prisma'), 'utf8');

if (!source.includes('provider = "postgresql"')) {
  throw new Error('Expected the canonical schema to use the postgresql provider');
}

const sqlite = [
  '// GENERATED by scripts/sqlite-schema.mjs from ../schema.prisma. Do not edit.',
  source
    .replace('provider = "postgresql"', 'provider = "sqlite"')
    .replace(/\s@db\.\w+(\([^)]*\))?/g, ''),
].join('\n');

const target = resolve(root, 'prisma/sqlite/schema.prisma');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, sqlite);
console.log(`sqlite schema written to ${target}`);
